pgrm2:main.o Class.o printClassGivenDay.o printClassGivenNumber.o printClassGivenProf.o
	gcc -o pgrm2 main.o Class.h printClassGivenDay.o printClassGivenNumber.o printClassGivenProf.o
 
main.o: main.c
	gcc -c -g -Wall main.c

Class.o: Class.h
	gcc -c -g -Wall Class.h

printClassGivenDay.o: printClassGivenDay.c
	gcc -c -g -Wall printClassGivenDay.c

printClassGivenNumber.o: printClassGivenNumber.c
	gcc -c -g -Wall printClassGivenNumber.c

printClassGivenProf.o: printClassGivenProf.c
	gcc -c -g -Wall printClassGivenProf.c


