pgm1: main.o readadd.o sortadd.o printinfo.o
	gcc -o pgm1 main.o readadd.o sortadd.o printinfo.o
main.o: main.c
	gcc -c main.c
readadd.o: readadd.c
	gcc -c readadd.c
sortadd.o: sortadd.c
	gcc -c sortadd.c
printinfo.o: printinfo.c
	gcc -c printinfo.c

