pgrm1:main.o sort.o classA.o classB.o classC.o
	gcc -o pgrm1 main.o sort.o classA.o classB.o classC.o

main.o: main.c
	gcc -c -Wall main.c

sort.o: sort.c
	gcc -c -Wall sort.c

classA.o: classA.c
	gcc -c -Wall classA.c

classB.o: classB.c
	gcc -c -Wall classB.c

classC.o: classC.c
	gcc -c -Wall classC.c
